uint16_t ghostRGB[] = {
GREEN,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		GREEN,		
BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		RED,		RED,		RED,		RED,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,
BLACK,		BLACK,		BLACK,		BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,		BLACK,		BLACK,		BLACK,
BLACK,		BLACK,		BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,		BLACK,		BLACK,
BLACK,		BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,		BLACK,
BLACK,		BLACK,		RED,		RED,		WHITE,		WHITE,		RED,		RED,		RED,		RED,		WHITE,		WHITE,		RED,		RED,		BLACK,		BLACK,
BLACK,		BLACK,		RED,		WHITE,		WHITE,		WHITE,		WHITE,		RED,		RED,		WHITE,		WHITE,		WHITE,		WHITE,		RED,		BLACK,		BLACK,
BLACK,		RED,		RED,		WHITE,		WHITE,		WHITE,		WHITE,		RED,		RED,		WHITE,		WHITE,		WHITE,		WHITE,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		WHITE,		BLUE,		BLUE,		WHITE,		RED,		RED,		WHITE,		BLUE,		BLUE,		WHITE,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		RED,		BLUE,		BLUE,		RED,		RED,		RED,		RED,		BLUE,		BLUE,		RED,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		RED,		BLACK,
BLACK,		RED,		RED,		BLACK,		RED,		RED,		RED,		BLACK,		BLACK,		RED,		RED,		RED,		BLACK,		RED,		RED,		BLACK,		
BLACK,		RED,		BLACK,		BLACK,		BLACK,		RED,		BLACK,		BLACK,		BLACK,		BLACK,		RED,		BLACK,		BLACK,		BLACK,		RED,		BLACK,
GREEN,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		BLACK,		GREEN};
static const sprite ghost = {
{16, 16}, ghostRGB};